const fs = require('fs');

// Read existing slangDatabase.ts to keep the 37 original hand-crafted ones intact
const existingTs = fs.readFileSync('src/data/slangDatabase.ts', 'utf8');

// Extract the original array items from existingTs
const firstArrayMatch = existingTs.match(/export const SLANG_DATABASE: SlangWord\[\] = \[([\s\S]*?)\];\s*export const CATEGORY_LABELS/);
if (!firstArrayMatch) {
  console.error("Could not find array in existing file");
  process.exit(1);
}

// 265 additional German slang terms categorized across all regions and categories
const extraSlang = [
  // JUGENDSPRACHE & MEMES
  {
    id: 'sus',
    term: 'Sus',
    meaningDe: 'Verdächtig, seltsam oder fragwürdig (aus Among Us).',
    meaningEn: 'Suspicious, shady, or weird.',
    literalTranslation: 'Short for suspicious',
    exampleDe: 'Wie er sich rausredet ist echt sus.',
    exampleEn: 'How he makes excuses is really sus.',
    scenario: {
      title: 'Beim Gruppenprojekt',
      speaker1: 'Mia',
      avatar1: 'cyber_chaya',
      text1: 'Warum hat Tom seine Kamera aus und tippt nicht mit?',
      speaker2: 'Leo',
      avatar2: 'hipster_macher',
      text2: 'Keine Ahnung, sein Verhalten ist übelst _____!',
      targetSlot: 'speaker2'
    },
    category: 'jugendsprache',
    region: 'all',
    rarity: 'common',
    isFamilyFriendly: true,
    hints: ['Aus dem Spiel Among Us', 'Bedeutet verdächtig', 'Nur 3 Buchstaben'],
    funFact: 'War Top 3 beim Jugendwort 2021.',
    distractors: ['Lost', 'Cringe', 'Safe', 'Gönn']
  },
  {
    id: 'goofy',
    term: 'Goofy',
    meaningDe: 'Tollpatschig, albern oder komisch.',
    meaningEn: 'Clumsy, silly, goofy or awkward.',
    literalTranslation: 'Like the Disney character Goofy',
    exampleDe: 'Sein Tanzmove sah so goofy aus.',
    exampleEn: 'His dance move looked so goofy.',
    scenario: {
      title: 'Auf der Tanzfläche',
      speaker1: 'Hannah',
      avatar1: 'party_kartoffel',
      text1: 'Guck mal wie er versucht zu breakdancen!',
      speaker2: 'Emil',
      avatar2: 'doener_king',
      text2: 'Voll der _____ Typ, aber sympathisch!',
      targetSlot: 'speaker2'
    },
    category: 'jugendsprache',
    region: 'all',
    rarity: 'common',
    isFamilyFriendly: true,
    hints: ['Jugendwort des Jahres 2023', 'Wie der Disney-Hund', 'Bedeutet albern'],
    funFact: 'Gewinner des Jugendwortes des Jahres 2023 in Deutschland.',
    distractors: ['Slay', 'Side-Eye', 'Rizz', 'NPC']
  },
  {
    id: 'rizz',
    term: 'Rizz',
    meaningDe: 'Die Fähigkeit zu flirten und Charme zu versprühen.',
    meaningEn: 'Romantic charm, flirting charisma, attractiveness.',
    literalTranslation: 'Short for Charisma',
    exampleDe: 'Er hat einfach unendlichen Rizz.',
    exampleEn: 'He just has infinite rizz.',
    scenario: {
      title: 'An der Bar',
      speaker1: 'Jan',
      avatar1: 'hipster_macher',
      text1: 'Er hat nach 2 Minuten ihre Nummer bekommen.',
      speaker2: 'Max',
      avatar2: 'cool_alman',
      text2: 'Unglaublich, der Junge hat ultimativen _____!',
      targetSlot: 'speaker2'
    },
    category: 'flirten',
    region: 'all',
    rarity: 'common',
    isFamilyFriendly: true,
    hints: ['Kommt von Cha-rizz-ma', 'Flirt-Fähigkeit', 'Jugendwort Top 2023'],
    funFact: 'Wurde von Streamer Kai Cenat populär gemacht.',
    distractors: ['Drip', 'Flex', 'Glow', 'Swag']
  },
  {
    id: 'npc',
    term: 'NPC',
    meaningDe: 'Person, die sich wie eine programmierte Spielfigur ohne eigene Meinung verhält.',
    meaningEn: 'Non-player character; someone acting basic or unoriginal.',
    literalTranslation: 'Non-Playable Character',
    exampleDe: 'Der Typ steht da rum wie ein NPC.',
    exampleEn: 'That dude is just standing there like an NPC.',
    scenario: {
      title: 'Im Einkaufszentrum',
      speaker1: 'Lisa',
      avatar1: 'cyber_chaya',
      text1: 'Warum läuft der Typ schon zum 5. Mal im Kreis?',
      speaker2: 'Ben',
      avatar2: 'berlin_bear',
      text2: 'Lass ihn, der ist im absoluten _____-Modus.',
      targetSlot: 'speaker2'
    },
    category: 'jugendsprache',
    region: 'all',
    rarity: 'common',
    isFamilyFriendly: true,
    hints: ['Gamer-Begriff', 'Non Player Character', 'Jemand ohne Eigeninitiative'],
    funFact: 'Bezieht sich auf Statisten in Open-World Videospielen.',
    distractors: ['Boss', 'Macher', 'Alman', 'Lauch']
  },
  {
    id: 'slay',
    term: 'Slay',
    meaningDe: 'Großartig aussehen oder etwas perfekt meistern.',
    meaningEn: 'To look amazing, do a stellar job, or impress everyone.',
    literalTranslation: 'To slay / conquer',
    exampleDe: 'Dein neues Outfit slayt komplett!',
    exampleEn: 'Your new outfit totally slays!',
    scenario: {
      title: 'Vor dem Ausgehen',
      speaker1: 'Laura',
      avatar1: 'cyber_chaya',
      text1: 'Wie gefällt dir meine Lederjacke mit den Boots?',
      speaker2: 'Sophie',
      avatar2: 'party_kartoffel',
      text2: 'Girl, du _____ heute Abend absolut!',
      targetSlot: 'speaker2'
    },
    category: 'flirten',
    region: 'all',
    rarity: 'common',
    isFamilyFriendly: true,
    hints: ['Kommt aus der Ballroom- & Pop-Kultur', 'Kompliment für Style', 'Jugendwort 2022/2023'],
    funFact: 'Aus der Queer- und Drag-Kultur in die globale Jugendsprache gewandert.',
    distractors: ['Cringe', 'Lost', 'Cap', 'Drop']
  },
  {
    id: 'side_eye',
    term: 'Side-Eye',
    meaningDe: 'Skeptischer, verurteilender Seitenblick.',
    meaningEn: 'Bombastic side-eye, judgmental side glance.',
    literalTranslation: 'Side eye glance',
    exampleDe: 'Sie hat mir den übelsten Side-Eye gegeben.',
    exampleEn: 'She gave me the most judgmental side-eye.',
    scenario: {
      title: 'In der Vorlesung',
      speaker1: 'Finn',
      avatar1: 'cool_alman',
      text1: 'Der Prof hat mich 10 Sekunden lang angestarrt, weil meine Chipstüte geraschelt hat.',
      speaker2: 'Paul',
      avatar2: 'hipster_macher',
      text2: 'Das war der klassische strafende _____!',
      targetSlot: 'speaker2'
    },
    category: 'jugendsprache',
    region: 'all',
    rarity: 'common',
    isFamilyFriendly: true,
    hints: ['TikTok-Trend "Bombastic..."', 'Blick zur Seite', 'Bedeutet Skepsis'],
    funFact: 'Wurde durch den TikTok-Audio "Bombastic side eye... criminal offensive side eye" weltberühmt.',
    distractors: ['Blickkontakt', 'Stare', 'Wink', 'High five']
  },
  {
    id: 'yolo',
    term: 'YOLO',
    meaningDe: 'Man lebt nur einmal (Motto für spontane, mutige Aktionen).',
    meaningEn: 'You Only Live Once.',
    literalTranslation: 'You Only Live Once',
    exampleDe: 'Komm wir buchen den Flug nach Mallorca, YOLO!',
    exampleEn: 'Come on let\'s book the flight to Mallorca, YOLO!',
    scenario: {
      title: 'Spontane Reiseplanung',
      speaker1: 'Simon',
      avatar1: 'party_kartoffel',
      text1: 'Soll ich wirklich mein ganzes Gehalt für das Festivalticket ausgeben?',
      speaker2: 'Lars',
      avatar2: 'doener_king',
      text2: 'Brudi mach einfach, _____!',
      targetSlot: 'speaker2'
    },
    category: 'feiern',
    region: 'all',
    rarity: 'common',
    isFamilyFriendly: true,
    hints: ['Jugendwort des Jahres 2012', 'Akronym aus 4 Wörtern', 'Bedeutet: Man lebt nur einmal'],
    funFact: 'Das allererste Jugendwort, das weltweit zur popkulturellen Redewendung wurde.',
    distractors: ['FOMO', 'TGIF', 'LOL', 'BRB']
  },
  {
    id: 'babo',
    term: 'Babo',
    meaningDe: 'Chef, Anführer, Respektsperson oder Boss.',
    meaningEn: 'Boss, leader, big shot.',
    literalTranslation: 'From Zazaki/Kurdish for father/boss',
    exampleDe: 'Haftbefehl ist der absolute Babo im Deutschrap.',
    exampleEn: 'Haftbefehl is the absolute boss in German rap.',
    scenario: {
      title: 'Im Viertel',
      speaker1: 'Tariq',
      avatar1: 'doener_king',
      text1: 'Wer regelt hier eigentlich die Dinge wenn es Stress gibt?',
      speaker2: 'Murat',
      avatar2: 'berlin_bear',
      text2: 'Onkel Cemal, er ist der wahre _____ hier.',
      targetSlot: 'speaker2'
    },
    category: 'schimpf_ehre',
    region: 'all',
    rarity: 'legendary',
    isFamilyFriendly: true,
    hints: ['Jugendwort des Jahres 2013', 'Chabos wissen wer der... ist', 'Bedeutet Boss'],
    funFact: 'Wurde durch Haftbefehls Megahit "Chabos wissen wer der Babo ist" legendär.',
    distractors: ['Lauch', 'Alman', 'Knilch', 'Opfer']
  },
  {
    id: 'smash',
    term: 'Smash',
    meaningDe: 'Mit jemandem etwas anfangen / attraktiv finden (aus Smash or Pass).',
    meaningEn: 'To hook up with someone, find someone very attractive.',
    literalTranslation: 'To smash (hook up)',
    exampleDe: 'Den neuen Schauspieler würde ich sofort smashen.',
    exampleEn: 'That new actor is an absolute smash.',
    scenario: {
      title: 'Serienabend',
      speaker1: 'Clara',
      avatar1: 'cyber_chaya',
      text1: 'Wie findest du den Hauptdarsteller?',
      speaker2: 'Zoe',
      avatar2: 'party_kartoffel',
      text2: 'Absoluter _____! Total mein Typ.',
      targetSlot: 'speaker2'
    },
    category: 'flirten',
    region: 'all',
    rarity: 'common',
    isFamilyFriendly: true,
    hints: ['Jugendwort des Jahres 2022', 'Gegenteil von Pass', 'Bedeutet heiß/attraktiv finden'],
    funFact: 'Jugendwort des Jahres 2022 in Deutschland.',
    distractors: ['Pass', 'Ghost', 'Skip', 'Block']
  },
  {
    id: 'cap',
    term: 'Cap',
    meaningDe: 'Lüge, erfunden oder Blödsinn (oft "No Cap" = ohne Witz).',
    meaningEn: 'Lie, fake, BS ("No cap" = no lie / for real).',
    literalTranslation: 'Cap (Lie)',
    exampleDe: 'Er meinte er hat 1000 Euro im Casino gewonnen – totaler Cap!',
    exampleEn: 'He said he won 1000 euros in the casino – total cap!',
    scenario: {
      title: 'Pausenhof-Geschichten',
      speaker1: 'Elias',
      avatar1: 'hipster_macher',
      text1: 'Ich schwöre ich bin gestern mit 300 km/h auf der Autobahn gefahren!',
      speaker2: 'Nico',
      avatar2: 'cool_alman',
      text2: 'Hör auf zu lügen, das ist 100% _____!',
      targetSlot: 'speaker2'
    },
    category: 'jugendsprache',
    region: 'all',
    rarity: 'common',
    isFamilyFriendly: true,
    hints: ['Englisches Slang-Wort', 'Gegenteil von Wahrheit', 'Oft als "No..." verwendet'],
    funFact: 'Wird oft mit dem Mützen-Emoji 🧢 symbolisiert.',
    distractors: ['Facts', 'Safe', 'Real', 'Legit']
  },
  {
    id: 'drip',
    term: 'Drip',
    meaningDe: 'Ein extrem stylisches, teures oder modisches Outfit.',
    meaningEn: 'Immense swag, high-fashion styling, cool outfit.',
    literalTranslation: 'Dripping with style',
    exampleDe: 'Seine neuen Sneaker geben ihm unfassbaren Drip.',
    exampleEn: 'His new sneakers give him insane drip.',
    scenario: {
      title: 'Vor dem Club',
      speaker1: 'Leon',
      avatar1: 'doener_king',
      text1: 'Guck dir mal seine Vintage-Jacke und die Kette an!',
      speaker2: 'David',
      avatar2: 'hipster_macher',
      text2: 'Brutal, der Junge hat heute maximalen _____!',
      targetSlot: 'speaker2'
    },
    category: 'jugendsprache',
    region: 'all',
    rarity: 'common',
    isFamilyFriendly: true,
    hints: ['Kommt aus dem Hip-Hop', 'Bedeutet stylisches Outfit', 'Wörtlich: Tropfen'],
    funFact: 'Im Deutschen sagt man oft "Der Drip ist real".',
    distractors: ['Drop', 'Flop', 'Drift', 'Dampf']
  },
  {
    id: 'flex',
    term: 'Flexen',
    meaningDe: 'Angeben, mit etwas prahlen oder Muskeln/Besitz zeigen.',
    meaningEn: 'To show off, boast, brag about possessions or status.',
    literalTranslation: 'To flex (muscles/wealth)',
    exampleDe: 'Er flext die ganze Zeit mit seiner neuen Uhr.',
    exampleEn: 'He is constantly flexing with his new watch.',
    scenario: {
      title: 'Im Fitnessstudio',
      speaker1: 'Marc',
      avatar1: 'hipster_macher',
      text1: 'Warum macht er 20 Selfies vor dem Spiegel?',
      speaker2: 'Tim',
      avatar2: 'berlin_bear',
      text2: 'Er will auf Insta mit seinem Bizeps _____!',
      targetSlot: 'speaker2'
    },
    category: 'jugendsprache',
    region: 'all',
    rarity: 'common',
    isFamilyFriendly: true,
    hints: ['Kommt aus der Gym- & Rapszene', 'Bedeutet prahlen', 'Verb zu Muskel anspannen'],
    funFact: 'Der "Weird Flex but OK"-Meme-Spruch ist auch im Deutschen sehr beliebt.',
    distractors: ['Chillen', 'Gönnen', 'Copen', 'Lurken']
  },
  {
    id: 'gong',
    term: 'Gönn dir',
    meaningDe: 'Tu dir etwas Gutes, genieße es oder greif zu!',
    meaningEn: 'Treat yourself, go for it, enjoy!',
    literalTranslation: 'Grant unto yourself',
    exampleDe: 'Du hast die Prüfung bestanden? Gönn dir Pizza!',
    exampleEn: 'You passed the exam? Treat yourself to pizza!',
    scenario: {
      title: 'In der Bäckerei',
      speaker1: 'Svenja',
      avatar1: 'party_kartoffel',
      text1: 'Soll ich wirklich noch das dritte Schokocroissant nehmen?',
      speaker2: 'Anna',
      avatar2: 'cyber_chaya',
      text2: 'Na klar, du hast hart trainiert – _____!',
      targetSlot: 'speaker2'
    },
    category: 'food_drinks',
    region: 'all',
    rarity: 'common',
    isFamilyFriendly: true,
    hints: ['Positiver Imperativ', 'Bedeutet: Verwöhne dich', 'Jugendwort 2014'],
    funFact: 'Jugendwort des Jahres 2014 ("Gönn dir!").',
    distractors: ['Schäm dich', 'Spar mal', 'Lass sein', 'Guck weg']
  },
  {
    id: 'alman',
    term: 'Alman',
    meaningDe: 'Stereotypischer, überkorrekter, pünktlicher oder spießiger Deutscher.',
    meaningEn: 'Stereotypical, rule-following, hyper-punctual German.',
    literalTranslation: 'Turkish for German (Almanya)',
    exampleDe: 'Er laminiert Beschwerden über Falschparker – richtiger Alman.',
    exampleEn: 'He laminates noise complaints – quintessential Alman.',
    scenario: {
      title: 'Am Sonntagmittag',
      speaker1: 'Kaan',
      avatar1: 'doener_king',
      text1: 'Herr Müller hat um 13:01 Uhr geklingelt, weil ich zu laut den Staubsauger anhatte.',
      speaker2: 'Dennis',
      avatar2: 'cool_alman',
      text2: 'Klassischer _____-Move wegen Mittagsruhe!',
      targetSlot: 'speaker2'
    },
    category: 'alman_kultur',
    region: 'all',
    rarity: 'common',
    isFamilyFriendly: true,
    hints: ['Türkisches Wort für Deutscher', 'Liebt Laminiergeräte & Pünktlichkeit', 'Popkulturelles Phänomen'],
    funFact: 'Der Instagram-Kanal @alman_memes hat über 700k Follower.',
    distractors: ['Babo', 'Chabo', 'Macher', 'Brudi']
  },
  {
    id: 'moin',
    term: 'Moin',
    meaningDe: 'Universeller norddeutscher Gruß zu jeder Tages- und Nachtzeit.',
    meaningEn: 'Universal northern German greeting for any time of day.',
    literalTranslation: 'From Low German "moi" (good/pleasant)',
    exampleDe: 'Moin! Wie geht die Arbeit voran?',
    exampleEn: 'Morning/Hello! How is work going?',
    scenario: {
      title: 'Um 23 Uhr an den Landungsbrücken',
      speaker1: 'Jan',
      avatar1: 'berlin_bear',
      text1: 'Sag mal, warum sagst du mitten in der Nacht Moin?',
      speaker2: 'Fiete',
      avatar2: 'cool_alman',
      text2: 'Weil _____ in Hamburg 24 Stunden am Tag gilt!',
      targetSlot: 'speaker2'
    },
    category: 'alman_kultur',
    region: 'nord',
    rarity: 'common',
    isFamilyFriendly: true,
    hints: ['Norddeutscher Kultgruß', 'Gilt auch um 3 Uhr nachts', 'Moin Moin gilt als Gesabbel'],
    funFact: 'Wer "Moin Moin" sagt, gilt im Norden bereits als geschwätzig.',
    distractors: ['Servus', 'Grüezi', 'Tach', 'Hallöchen']
  },
  {
    id: 'servus',
    term: 'Servus',
    meaningDe: 'Traditioneller bayerischer & österreichischer Gruß (Hallo & Tschüss).',
    meaningEn: 'Traditional Bavarian/Austrian greeting (both hello and goodbye).',
    literalTranslation: 'From Latin "servus" (at your service)',
    exampleDe: 'Servus beinand, schee dass ma uns seng!',
    exampleEn: 'Greetings everyone, great to see each other!',
    scenario: {
      title: 'Im Biergarten',
      speaker1: 'Hans',
      avatar1: 'cool_alman',
      text1: 'Griaß di! Setz di her zu uns!',
      speaker2: 'Sepp',
      avatar2: 'party_kartoffel',
      text2: '_____, bringst ma glei a Helles mit?',
      targetSlot: 'speaker2'
    },
    category: 'alman_kultur',
    region: 'bayern',
    rarity: 'common',
    isFamilyFriendly: true,
    hints: ['Bayerisch & Österreichisch', 'Bedeutet Hallo und Auf Wiedersehen', 'Kommt aus dem Lateinischen'],
    funFact: 'Wird in Bayern, Österreich und Teilen Frankens gleichermaßen verwendet.',
    distractors: ['Moin', 'Tschö', 'Ahoi', 'Adieu']
  },
  {
    id: 'gruetzi',
    term: 'Grüezi',
    meaningDe: 'Klassischer Schweizer Höflichkeitsgruß.',
    meaningEn: 'Classic Swiss German polite greeting.',
    literalTranslation: 'Gott grüez di (May God greet you)',
    exampleDe: 'Grüezi mitenand, wie goht\'s?',
    exampleEn: 'Hello everyone, how are you doing?',
    scenario: {
      title: 'In der Zürcher Altstadt',
      speaker1: 'Beat',
      avatar1: 'hipster_macher',
      text1: 'Willkommen in der Schweiz!',
      speaker2: 'Urs',
      avatar2: 'cool_alman',
      text2: '_____ wohl, schön sind Sie da!',
      targetSlot: 'speaker2'
    },
    category: 'alman_kultur',
    region: 'schweiz',
    rarity: 'common',
    isFamilyFriendly: true,
    hints: ['Schweizer Gruß', 'Sehr höflich', 'Für mehrere Personen: Grüezi mitenand'],
    funFact: 'Unter Freunden sagt man in der Schweiz stattdessen "Hoi" oder "Sali".',
    distractors: ['Moin', 'Servus', 'Tach', 'Guten Tag']
  },
  {
    id: 'oida',
    term: 'Oida',
    meaningDe: 'Das ultimative Wiener Universalwort für alle Emotionen (Alter/Dude).',
    meaningEn: 'Viennese universal expression for anger, joy, surprise, or dude.',
    literalTranslation: 'Alter (Old one / Dude)',
    exampleDe: 'Oida, bist du deppert oder was?!',
    exampleEn: 'Dude, are you completely insane?!',
    scenario: {
      title: 'In der Wiener U-Bahn',
      speaker1: 'Florian',
      avatar1: 'berlin_bear',
      text1: 'Jemand hat gerade meine Melange umgestoßen!',
      speaker2: 'Moritz',
      avatar2: 'party_kartoffel',
      text2: '_____, na das gibt\'s doch nicht!',
      targetSlot: 'speaker2'
    },
    category: 'alman_kultur',
    region: 'wien',
    rarity: 'legendary',
    isFamilyFriendly: true,
    hints: ['Wiener Kultwort', 'Kann wütend, erfreut oder überrascht klingen', 'Österreichische Version von Digga/Alter'],
    funFact: 'Es gibt virale Videos, die zeigen, dass "Oida" in 50 verschiedenen Tonlagen alles ausdrücken kann.',
    distractors: ['Brudi', 'Digga', 'Kollege', 'Kumpel']
  },
  {
    id: 'kiez',
    term: 'Kiez',
    meaningDe: 'Das eigene Wohnviertel oder Kiezviertel (besonders Berlin & Hamburg).',
    meaningEn: 'Neighborhood, local hood, quarter.',
    literalTranslation: 'Slavic origin for fishermen village / neighborhood',
    exampleDe: 'Ich verlasse meinen Kiez in Kreuzberg fast nie.',
    exampleEn: 'I almost never leave my neighborhood in Kreuzberg.',
    scenario: {
      title: 'Spaziergang am Sonntag',
      speaker1: 'Marlene',
      avatar1: 'cyber_chaya',
      text1: 'Wo gibt es hier den besten Kaffee?',
      speaker2: 'Nils',
      avatar2: 'hipster_macher',
      text2: 'Hier bei uns im _____ hat jedes Café Hafermilch!',
      targetSlot: 'speaker2'
    },
    category: 'jugendsprache',
    region: 'berlin',
    rarity: 'common',
    isFamilyFriendly: true,
    hints: ['Berliner & Hamburger Begriff', 'Bezeichnet das Viertel/Wohngebiet', 'Kiez-Kultur'],
    funFact: 'In Berlin hat jeder Kiez seinen ganz eigenen Charakter und Stolz.',
    distractors: ['Dorf', 'City', 'Ghetto', 'Block']
  },
  {
    id: 'spaeti',
    term: 'Späti',
    meaningDe: 'Spätkauf / Kiosk, der bis tief in die Nacht oder 24/7 geöffnet hat.',
    meaningEn: 'Late-night corner convenience store / kiosk in Berlin.',
    literalTranslation: 'Short for Spätverkaufsstelle (Late sales point)',
    exampleDe: 'Lass noch schnell zum Späti und Club-Mate holen.',
    exampleEn: 'Let\'s quickly hit the Späti and grab Club-Mate.',
    scenario: {
      title: 'Freitagabend um 01:30 Uhr',
      speaker1: 'Jonas',
      avatar1: 'doener_king',
      text1: 'Alle Supermärkte haben schon lange zu!',
      speaker2: 'Can',
      avatar2: 'berlin_bear',
      text2: 'Kein Problem, der _____ an der Ecke hat die ganze Nacht auf.',
      targetSlot: 'speaker2'
    },
    category: 'feiern',
    region: 'berlin',
    rarity: 'common',
    isFamilyFriendly: true,
    hints: ['Berliner Institution', 'Hat nachts geöffnet', 'Gibt es Bier, Mate und Snacks'],
    funFact: 'Entstand in der DDR als Spätverkaufsstelle für Schichtarbeiter.',
    distractors: ['Supermarkt', 'Boutique', 'Apotheke', 'Bäcker']
  }
];

// Let's create a programmatic generator to build an encyclopedic list of 305 total words
// Categories: 'jugendsprache', 'feiern', 'flirten', 'schule_arbeit', 'food_drinks', 'alman_kultur', 'schimpf_ehre'
// Regions: 'all', 'berlin', 'bayern', 'ruhrpott', 'nord', 'wien', 'schweiz'

const additionalVocabList = [
  // Youth / Street / Slang
  { term: 'Aura', id: 'aura', meaningDe: 'Die persönliche Ausstrahlung, Coolness oder soziale Präsenz (oft "+1000 Aura" oder "-500 Aura").', meaningEn: 'Personal charisma, cool vibe or energy points.', cat: 'jugendsprache', reg: 'all', rar: 'common' },
  { term: 'Delulu', id: 'delulu', meaningDe: 'Wahnhaft, unrealistisch oder in einer Traumwelt lebend.', meaningEn: 'Delusional, unrealistic, daydreaming.', cat: 'jugendsprache', reg: 'all', rar: 'common' },
  { term: 'Glow Up', id: 'glow_up', meaningDe: 'Eine drastische optische oder persönliche positive Verwandlung.', meaningEn: 'Major positive transformation in looks or confidence.', cat: 'flirten', reg: 'all', rar: 'common' },
  { term: 'Sheesh', id: 'sheesh', meaningDe: 'Ausruf des Erstaunens, Respekts oder der Fassungslosigkeit.', meaningEn: 'Expression of disbelief, amazement or hype.', cat: 'jugendsprache', reg: 'all', rar: 'common' },
  { term: 'Bodenlos', id: 'bodenlos', meaningDe: 'Unglaublich schlecht, unverschämt oder bodenlos frech.', meaningEn: 'Abysmal, utterly shameless, bottomless.', cat: 'jugendsprache', reg: 'all', rar: 'common' },
  { term: 'Sippen', id: 'sippen', meaningDe: 'Genüsslich in kleinen Schlucken trinken (oft Softdrinks oder Drinks).', meaningEn: 'To sip slowly on a drink.', cat: 'food_drinks', reg: 'all', rar: 'common' },
  { term: 'Vorglühen', id: 'vorgluehen', meaningDe: 'Zuhause mit Freunden vor dem Feiern im Club Alkohol trinken.', meaningEn: 'Pre-gaming / pre-drinking before going out to a club.', cat: 'feiern', reg: 'all', rar: 'common' },
  { term: 'Kater', id: 'kater', meaningDe: 'Das Unwohlsein und die Kopfschmerzen am Tag nach einer durchzechten Nacht.', meaningEn: 'Hangover the day after heavy drinking.', cat: 'feiern', reg: 'all', rar: 'common' },
  { term: 'Lauch', id: 'lauch', meaningDe: 'Schlaksige, unsportliche Person ohne Muskeln oder Durchsetzungsvermögen.', meaningEn: 'Scrawny person, weakling, wimp.', cat: 'schimpf_ehre', reg: 'all', rar: 'common' },
  { term: 'Brudi', id: 'brudi', meaningDe: 'Bruder, Kumpel, enger Freund oder vertraute Anrede.', meaningEn: 'Bro, brother, homie.', cat: 'jugendsprache', reg: 'all', rar: 'common' },
  { term: 'Chabo', id: 'chabo', meaningDe: 'Junge, Kerl oder Typ aus dem Viertel.', meaningEn: 'Guy, boy, dude from the hood.', cat: 'jugendsprache', reg: 'all', rar: 'rare' },
  { term: 'Wallah', id: 'wallah', meaningDe: 'Schwur-Wort ("Ich schwöre bei Gott"), um die absolute Wahrheit zu betonen.', meaningEn: 'I swear to God / for real.', cat: 'jugendsprache', reg: 'all', rar: 'common' },
  { term: 'Habibi', id: 'habibi', meaningDe: 'Liebling, Schatz oder herzliche Anrede für gute Freunde.', meaningEn: 'My love, darling, or dear friend.', cat: 'flirten', reg: 'all', rar: 'common' },
  { term: 'Yarak', id: 'yarak', meaningDe: 'Kraftausdruck aus dem Türkischen, oft als starkes Schimpfwort genutzt.', meaningEn: 'Harsh curse word / swear word.', cat: 'schimpf_ehre', reg: 'all', rar: 'rare' },
  { term: 'Para machen', id: 'para_machen', meaningDe: 'Viel Geld verdienen oder Scheine machen.', meaningEn: 'To make bank, earn serious money.', cat: 'schule_arbeit', reg: 'all', rar: 'common' },
  { term: 'Asi', id: 'asi', meaningDe: 'Asozial, rücksichtslos, vulgär oder ungehobelt.', meaningEn: 'Anti-social, trashy, ill-mannered.', cat: 'schimpf_ehre', reg: 'all', rar: 'common' },
  { term: 'Geringverdiener', id: 'geringverdiener', meaningDe: 'Scherzhafte Abwertung für Leute, die sparen oder günstige Sachen kaufen.', meaningEn: 'Low earner (used jokingly for penny pinchers).', cat: 'schule_arbeit', reg: 'all', rar: 'rare' },
  { term: 'Gönnung', id: 'goennung', meaningDe: 'Ein purer Luxus oder Genussmoment.', meaningEn: 'A pure treat or indulgence.', cat: 'food_drinks', reg: 'all', rar: 'common' },
  { term: 'Cornern', id: 'cornern', meaningDe: 'Mit Freunden und einem Kioskbier an einer Straßenecke abhängen.', meaningEn: 'Hanging out on a street corner with drinks.', cat: 'feiern', reg: 'berlin', rar: 'common' },
  { term: 'Ballern', id: 'ballern', meaningDe: 'Extrem reinhauen, knallen (laute Musik, Alkohol oder schnelles Fahren).', meaningEn: 'To bang hard, hit intensely, or blast music.', cat: 'feiern', reg: 'all', rar: 'common' },
  { term: 'Absturz', id: 'absturz', meaningDe: 'Eine Party-Nacht, die völlig aus dem Ruder gelaufen ist.', meaningEn: 'Complete drunken crash / blackout night.', cat: 'feiern', reg: 'all', rar: 'common' },
  { term: 'Pumper', id: 'pumper', meaningDe: 'Jemand, der extrem viel Zeit mit Krafttraining im Fitnessstudio verbringt.', meaningEn: 'Bodybuilder, gym bro.', cat: 'jugendsprache', reg: 'all', rar: 'common' },
  { term: 'Gymrat', id: 'gymrat', meaningDe: 'Fitnessstudio-Süchtiger, der fast im Gym wohnt.', meaningEn: 'Gym rat, obsessive workout fanatic.', cat: 'jugendsprache', reg: 'all', rar: 'common' },
  { term: 'Auf Krampf', id: 'auf_krampf', meaningDe: 'Etwas mit aller Gewalt erzwingen wollen, obwohl es keinen Sinn macht.', meaningEn: 'Forcing something unnaturally / tryhard.', cat: 'jugendsprache', reg: 'all', rar: 'common' },
  { term: 'Chillig', id: 'chillig', meaningDe: 'Entspannt, angenehm, gemütlich.', meaningEn: 'Chill, relaxed, cozy.', cat: 'jugendsprache', reg: 'all', rar: 'common' },
  { term: 'Pennen', id: 'pennen', meaningDe: 'Schlafen oder dösen.', meaningEn: 'To sleep, crash, doze.', cat: 'jugendsprache', reg: 'all', rar: 'common' },
  { term: 'Baff', id: 'baff', meaningDe: 'Völlig sprachlos, überrascht oder verblüfft.', meaningEn: 'Stunned, flabbergasted, speechless.', cat: 'jugendsprache', reg: 'all', rar: 'common' },
  { term: 'Zappeln', id: 'zappeln', meaningDe: 'Tanzen oder nervös herumhampeln.', meaningEn: 'To dance or fidget nervously.', cat: 'feiern', reg: 'all', rar: 'rare' },
  { term: 'Pegel', id: 'pegel', meaningDe: 'Der aktuelle Alkohol-Zustand beim Feiern.', meaningEn: 'Current buzz or blood alcohol level.', cat: 'feiern', reg: 'all', rar: 'common' },
  { term: 'Voll wie eine Haubitze', id: 'haubitze', meaningDe: 'Extrem stark betrunken sein.', meaningEn: 'Wasted / hammered drunk.', cat: 'feiern', reg: 'all', rar: 'legendary' },
  { term: 'Keine Peilung', id: 'keine_peilung', meaningDe: 'Keinerlei Ahnung oder Orientierung haben.', meaningEn: 'Having zero clue or understanding.', cat: 'schule_arbeit', reg: 'all', rar: 'common' },
  { term: 'Kein Bock', id: 'kein_bock', meaningDe: 'Absolute Unlust oder Demotivation.', meaningEn: 'Zero desire / cannot be bothered.', cat: 'schule_arbeit', reg: 'all', rar: 'common' },
  { term: 'Blaumachen', id: 'blaumachen', meaningDe: 'Unentschuldigt der Arbeit oder Schule fernbleiben.', meaningEn: 'Skipping work or school, playing truant.', cat: 'schule_arbeit', reg: 'all', rar: 'common' },
  { term: 'Durchziehen', id: 'durchziehen', meaningDe: 'Eine schwierige Aufgabe bis zum Ende ohne Pause durchhalten.', meaningEn: 'Powering through to the finish line.', cat: 'schule_arbeit', reg: 'all', rar: 'common' },
  { term: 'Streber', id: 'streber', meaningDe: 'Überambitionierter Schüler oder Student.', meaningEn: 'Overachiever, nerd, teacher\'s pet.', cat: 'schule_arbeit', reg: 'all', rar: 'common' },
  { term: 'Verpeilt', id: 'verpeilt', meaningDe: 'Zerstreut, unkonzentriert, vergesslich.', meaningEn: 'Scatterbrained, dazed, clumsy.', cat: 'jugendsprache', reg: 'all', rar: 'common' },
  { term: 'Schmatzen', id: 'schmatzen', meaningDe: 'Laut essen oder ein herzhafter Kuss.', meaningEn: 'Chewing noisily or a smack kiss.', cat: 'food_drinks', reg: 'all', rar: 'common' },
  { term: 'Fressflash', id: 'fressflash', meaningDe: 'Plötzlicher unkontrollierbarer Heißhunger.', meaningEn: 'Munchies, sudden binge eating craving.', cat: 'food_drinks', reg: 'all', rar: 'common' },
  { term: 'Schrippe', id: 'schrippe', meaningDe: 'Berliner Bezeichnung für ein einfaches Weizenbrötchen.', meaningEn: 'Berlin word for bread roll.', cat: 'food_drinks', reg: 'berlin', rar: 'common' },
  { term: 'Semmel', id: 'semmel', meaningDe: 'Bayerische & österreichische Bezeichnung für Brötchen.', meaningEn: 'Bavarian/Austrian bread roll.', cat: 'food_drinks', reg: 'bayern', rar: 'common' },
  { term: 'Weck', id: 'weck', meaningDe: 'Südwestdeutsches Wort für Brötchen.', meaningEn: 'Southwestern German bread roll.', cat: 'food_drinks', reg: 'all', rar: 'rare' },
  { term: 'Currywurst', id: 'currywurst', meaningDe: 'Kult-Imbiss: Bratwurst mit Currysauce und Pulver.', meaningEn: 'Iconic curry spiced sausage snack.', cat: 'food_drinks', reg: 'berlin', rar: 'common' },
  { term: 'Döner mit allem', id: 'doener_komplett', meaningDe: 'Der klassische Döner mit allen Salaten und scharfer Soße.', meaningEn: 'Doner kebab with all salads and spicy sauce.', cat: 'food_drinks', reg: 'all', rar: 'common' },
  { term: 'Ayran', id: 'ayran', meaningDe: 'Erfrischendes türkisches Joghurtgetränk mit Salz.', meaningEn: 'Salted yogurt drink paired with doner.', cat: 'food_drinks', reg: 'all', rar: 'common' },
  { term: 'Wegbier', id: 'wegbier', meaningDe: 'Flasche Bier, die man unterwegs zu Fuß trinkt.', meaningEn: 'Beer consumed while walking to the next destination.', cat: 'feiern', reg: 'all', rar: 'common' },
  { term: 'Komasaufen', id: 'komasaufen', meaningDe: 'Extremes Rauschtrinken bis zur Bewusstlosigkeit.', meaningEn: 'Binge drinking to extreme stupor.', cat: 'feiern', reg: 'all', rar: 'rare' },
  { term: 'Abhotten', id: 'abhotten', meaningDe: 'Wild und ausgelassen tanzen.', meaningEn: 'Dancing wildly on the dance floor.', cat: 'feiern', reg: 'all', rar: 'rare' },
  { term: 'Mucke', id: 'mucke', meaningDe: 'Umgangssprachlich für Musik oder Tunes.', meaningEn: 'Music, beats, tunes.', cat: 'feiern', reg: 'all', rar: 'common' },
  { term: 'Feierabendbier', id: 'feierabendbier', meaningDe: 'Das traditionelle Bier direkt nach getaner Arbeit.', meaningEn: 'The traditional post-work beer.', cat: 'food_drinks', reg: 'all', rar: 'common' },
  { term: 'Stammtisch', id: 'stammtisch', meaningDe: 'Feste Gruppe von Stammgästen am reservierten Wirtshaustisch.', meaningEn: 'Regulars\' table at a local tavern.', cat: 'alman_kultur', reg: 'bayern', rar: 'common' },
  { term: 'Mass Bier', id: 'mass_bier', meaningDe: 'Ein Liter Bier im schweren Glaskrug (auf dem Oktoberfest).', meaningEn: 'One liter of beer in a heavy glass stein.', cat: 'food_drinks', reg: 'bayern', rar: 'common' },
  { term: 'Grias Di', id: 'grias_di', meaningDe: 'Grüß dich auf Bayerisch / Österreichisch.', meaningEn: 'Greetings / hello in Alpine dialect.', cat: 'alman_kultur', reg: 'bayern', rar: 'common' },
  { term: 'Pfiat Di', id: 'pfiat_di', meaningDe: 'Behüte dich Gott (Auf Wiedersehen auf Bayerisch).', meaningEn: 'Goodbye / God protect you in Bavarian.', cat: 'alman_kultur', reg: 'bayern', rar: 'common' },
  { term: 'Schmarrn', id: 'schmarrn', meaningDe: 'Unsinn, Quatsch oder traditionelle Süßspeise (Kaiserschmarrn).', meaningEn: 'Nonsense, rubbish, or shredded pancake dish.', cat: 'alman_kultur', reg: 'bayern', rar: 'common' },
  { term: 'Gaudi', id: 'gaudi', meaningDe: 'Großer Spaß, ausgelassene Stimmung oder Unterhaltung.', meaningEn: 'Great fun, merrymaking, entertainment.', cat: 'alman_kultur', reg: 'bayern', rar: 'common' },
  { term: 'Bazi', id: 'bazi', meaningDe: 'Schlingel, Schlauberger oder liebenswerter Gauner.', meaningEn: 'Rascal, cheeky rogue, clever fellow.', cat: 'alman_kultur', reg: 'bayern', rar: 'rare' },
  { term: 'Grantler', id: 'grantler', meaningDe: 'Mürrischer, ständig nörgelnder älterer Mann in Bayern.', meaningEn: 'Grumpy, constantly complaining Bavarian man.', cat: 'alman_kultur', reg: 'bayern', rar: 'rare' },
  { term: 'Oachkatzlschwoaf', id: 'oachkatzlschwoaf', meaningDe: 'Eichhörnchenschweif (berühmtester bayerischer Dialekt-Test).', meaningEn: 'Squirrel tail (famous Bavarian shibboleth).', cat: 'alman_kultur', reg: 'bayern', rar: 'legendary' },
  { term: 'Brezn', id: 'brezn', meaningDe: 'Bayerische Laugenbrezel mit grobem Salz.', meaningEn: 'Bavarian salted pretzel.', cat: 'food_drinks', reg: 'bayern', rar: 'common' },
  { term: 'Weisswurst', id: 'weisswurst', meaningDe: 'Münchner Spezialität aus Kalbfleisch, vor 12 Uhr gegessen.', meaningEn: 'Traditional Bavarian white veal sausage.', cat: 'food_drinks', reg: 'bayern', rar: 'common' },
  { term: 'Zuzeln', id: 'zuzeln', meaningDe: 'Das traditionelle Aussaugen der Weißwurst aus der Haut.', meaningEn: 'Sucking the white sausage out of its casing.', cat: 'food_drinks', reg: 'bayern', rar: 'rare' },
  { term: 'Helles', id: 'helles', meaningDe: 'Mildes, untergäriges bayerisches Lagerbier.', meaningEn: 'Crisp, pale traditional Bavarian lager.', cat: 'food_drinks', reg: 'bayern', rar: 'common' },
  { term: 'Radler', id: 'radler', meaningDe: 'Bier gemischt mit Zitronenlimonade.', meaningEn: 'Shandy (beer mixed with lemon soda).', cat: 'food_drinks', reg: 'all', rar: 'common' },
  { term: 'Spezi', id: 'spezi', meaningDe: 'Kult-Mixgetränk aus Cola und Orangenlimonade.', meaningEn: 'Iconic German mix of cola and orange soda.', cat: 'food_drinks', reg: 'all', rar: 'common' },
  { term: 'Apfelschorle', id: 'apfelschorle', meaningDe: 'Apfelsaft gemischt mit sprudelndem Mineralwasser.', meaningEn: 'Apple juice mixed with sparkling water.', cat: 'food_drinks', reg: 'all', rar: 'common' },
  { term: 'Club-Mate', id: 'club_mate', meaningDe: 'Kohlensäurehaltiges Mate-Kultgetränk der Berliner Clubkultur.', meaningEn: 'Caffeinated sparkling mate tea soda.', cat: 'food_drinks', reg: 'berlin', rar: 'common' },
  { term: 'Berliner Luft', id: 'berliner_luft', meaningDe: 'Klarer Pfefferminzlikör, Kult-Shot im Berliner Nachtleben.', meaningEn: 'Iconic clear peppermint schnapps from Berlin.', cat: 'feiern', reg: 'berlin', rar: 'common' },
  { term: 'Sterni', id: 'sterni', meaningDe: 'Sternburg Export – das legendäre günstige Kultbier im Osten.', meaningEn: 'Sternburg Export, famous cheap cult beer.', cat: 'food_drinks', reg: 'berlin', rar: 'common' },
  { term: 'Dit is Berlin', id: 'dit_is_berlin', meaningDe: 'Ausruf für skurrile, typisch verrückte Alltagssituationen in Berlin.', meaningEn: 'That\'s classic quirky Berlin for you.', cat: 'alman_kultur', reg: 'berlin', rar: 'common' },
  { term: 'Atze', id: 'atze', meaningDe: 'Berliner Kumpel, Bruder oder bester Freund.', meaningEn: 'Berlin homie, pal, close buddy.', cat: 'jugendsprache', reg: 'berlin', rar: 'common' },
  { term: 'Keule', id: 'keule', meaningDe: 'Berliner Kosewort für jüngerer Bruder oder Kumpel.', meaningEn: 'Berlin slang for younger brother / pal.', cat: 'jugendsprache', reg: 'berlin', rar: 'rare' },
  { term: 'Icke', id: 'icke', meaningDe: 'Berliner Mundart für "Ich".', meaningEn: 'Berlin dialect for "Me / I".', cat: 'alman_kultur', reg: 'berlin', rar: 'common' },
  { term: 'Jottwedee', id: 'jottwedee', meaningDe: 'Janz weit draußen (sehr weit außerhalb der Stadt).', meaningEn: 'Way out in the middle of nowhere.', cat: 'alman_kultur', reg: 'berlin', rar: 'rare' },
  { term: 'Schwofen', id: 'schwofen', meaningDe: 'Altberliner Begriff für gemütlich tanzen gehen.', meaningEn: 'Old Berlin term for social dancing.', cat: 'feiern', reg: 'berlin', rar: 'rare' },
  { term: 'Koffern', id: 'koffern', meaningDe: 'Mit voller Wucht schlagen oder rennen.', meaningEn: 'To slam, strike hard or rush.', cat: 'jugendsprache', reg: 'ruhrpott', rar: 'rare' },
  { term: 'Kumpel', id: 'kumpel_pott', meaningDe: 'Bergmann im Ruhrgebiet, heute universell für Freund.', meaningEn: 'Miner in the Ruhr area, now universal friend.', cat: 'alman_kultur', reg: 'ruhrpott', rar: 'common' },
  { term: 'Glückauf', id: 'glueckauf', meaningDe: 'Traditioneller Bergmannsgruß im Ruhrgebiet.', meaningEn: 'Traditional German miners\' greeting of good luck.', cat: 'alman_kultur', reg: 'ruhrpott', rar: 'common' },
  { term: 'Malochen', id: 'malochen', meaningDe: 'Schwer und hart körperlich arbeiten.', meaningEn: 'To toil, work hard manually.', cat: 'schule_arbeit', reg: 'ruhrpott', rar: 'common' },
  { term: 'Bude', id: 'bude_pott', meaningDe: 'Trinkhalle / Kiosk im Ruhrgebiet oder die eigene Wohnung.', meaningEn: 'Kiosk / newsstand in Ruhr area or one\'s flat.', cat: 'feiern', reg: 'ruhrpott', rar: 'common' },
  { term: 'Pilsken', id: 'pilsken', meaningDe: 'Ein kleines, frisch gezapftes Pilsbier im Pott.', meaningEn: 'A nice cold draft Pilsner beer.', cat: 'food_drinks', reg: 'ruhrpott', rar: 'common' },
  { term: 'Manta-Platte', id: 'manta_platte', meaningDe: 'Currywurst mit Pommes rot-weiß im Ruhrgebiet.', meaningEn: 'Currywurst with fries ketchup & mayo.', cat: 'food_drinks', reg: 'ruhrpott', rar: 'legendary' },
  { term: 'Klappspaten', id: 'klappspaten', meaningDe: 'Umgangssprachlich für einen ungeschickten Dummkopf.', meaningEn: 'Fool, dimwit, clumsy idiot.', cat: 'schimpf_ehre', reg: 'all', rar: 'common' },
  { term: 'Vollpfosten', id: 'vollpfosten', meaningDe: 'Totaler Idiot oder unbegabte Person.', meaningEn: 'Complete idiot, total dummy.', cat: 'schimpf_ehre', reg: 'all', rar: 'common' },
  { term: 'Honk', id: 'honk', meaningDe: 'Hauptschüler ohne nennenswerte Kenntnisse (Idiot).', meaningEn: 'Clueless person, blockhead.', cat: 'schimpf_ehre', reg: 'all', rar: 'common' },
  { term: 'Pflaume', id: 'pflaume', meaningDe: 'Tollpatsch oder weichliche Person.', meaningEn: 'Softie, clumsy person, wuss.', cat: 'schimpf_ehre', reg: 'all', rar: 'common' },
  { term: 'Spacko', id: 'spacko', meaningDe: 'Alberner oder nerviger Spinner.', meaningEn: 'Weirdo, hyperactive goofball.', cat: 'schimpf_ehre', reg: 'all', rar: 'common' },
  { term: 'Evolutionsbremse', id: 'evolutionsbremse', meaningDe: 'Sarkastische Bezeichnung für besonders unkluge Menschen.', meaningEn: 'Brake of evolution (sarcastic insult).', cat: 'schimpf_ehre', reg: 'all', rar: 'rare' },
  { term: 'Warmduscher', id: 'warmduscher', meaningDe: 'Verweichlichte Person, die keine Härte erträgt.', meaningEn: 'Wimp, someone who takes warm showers.', cat: 'schimpf_ehre', reg: 'all', rar: 'common' },
  { term: 'Schattenparker', id: 'schattenparker', meaningDe: 'Übervorsichtiger Mensch, der jedes Risiko meidet.', meaningEn: 'Overcautious person (parks in shade).', cat: 'schimpf_ehre', reg: 'all', rar: 'common' },
  { term: 'Beckenrandschwimmer', id: 'beckenrandschwimmer', meaningDe: 'Feigling, der immer am sicheren Beckenrand bleibt.', meaningEn: 'Coward (clings to pool edge).', cat: 'schimpf_ehre', reg: 'all', rar: 'common' },
  { term: 'Sitzpinkler', id: 'sitzpinkler', meaningDe: 'Spottname für übermäßig brave oder angepasste Männer.', meaningEn: 'Overly docile or timid man.', cat: 'schimpf_ehre', reg: 'all', rar: 'common' },
  { term: 'Lümmel', id: 'luemmel', meaningDe: 'Frecher Bengel oder umgangssprachlich Schlingel.', meaningEn: 'Cheeky rascal, rogue.', cat: 'schimpf_ehre', reg: 'all', rar: 'rare' },
  { term: 'Dödel', id: 'doedel', meaningDe: 'Gutartiger Dummkopf oder Trottel.', meaningEn: 'Silly goose, dimwit, doofus.', cat: 'schimpf_ehre', reg: 'all', rar: 'common' },
  { term: 'Knalltüte', id: 'knalltuete', meaningDe: 'Unberechenbare oder verrückte Person.', meaningEn: 'Nutjob, eccentric goofball.', cat: 'schimpf_ehre', reg: 'all', rar: 'common' },
  { term: 'Pappnase', id: 'pappnase', meaningDe: 'Trottel (ursprünglich aus dem Kölner Karneval).', meaningEn: 'Clown, fool (carnival origin).', cat: 'schimpf_ehre', reg: 'all', rar: 'common' },
  { term: 'Heulsuse', id: 'heulsuse', meaningDe: 'Person, die wegen jeder Kleinigkeit jammert.', meaningEn: 'Crybaby, whiner.', cat: 'schimpf_ehre', reg: 'all', rar: 'common' },
  { term: 'Zicke', id: 'zicke', meaningDe: 'Launische, zickige oder empfindliche Person.', meaningEn: 'Moody, feisty, difficult person.', cat: 'schimpf_ehre', reg: 'all', rar: 'common' },
  { term: 'Schlaftablette', id: 'schlaftablette', meaningDe: 'Sehr langsame, lethargische Person.', meaningEn: 'Slowpoke, lethargic person.', cat: 'schimpf_ehre', reg: 'all', rar: 'common' },
  { term: 'Schnarchnase', id: 'schnarchnase', meaningDe: 'Schläfriger Mensch, der zu spät reagiert.', meaningEn: 'Sleepyhead, slow-witted person.', cat: 'schimpf_ehre', reg: 'all', rar: 'common' },
  { term: 'Tratschtante', id: 'tratschtante', meaningDe: 'Jemand, der ständig Gerüchte weiterträgt.', meaningEn: 'Gossip, busybody.', cat: 'jugendsprache', reg: 'all', rar: 'common' },
  { term: 'Petze', id: 'petze', meaningDe: 'Jemand, der Geheimnisse an Lehrer oder Chefs verrät.', meaningEn: 'Tattletale, snitch.', cat: 'schule_arbeit', reg: 'all', rar: 'common' },
  { term: 'Querulant', id: 'querulant', meaningDe: 'Jemand, der aus Prinzip ständig Widerspruch einlegt.', meaningEn: 'Habitual complainer, troublemaker.', cat: 'alman_kultur', reg: 'all', rar: 'rare' },
  { term: 'Tüddelig', id: 'tueddelig', meaningDe: 'Norddeutsch für verwirrt, vergesslich oder schusselig.', meaningEn: 'Confused, doddery, forgetful (Northern).', cat: 'alman_kultur', reg: 'nord', rar: 'common' },
  { term: 'Schnacken', id: 'schnacken', meaningDe: 'Norddeutsch für sich unterhalten oder plaudern.', meaningEn: 'To chat, converse (Northern German).', cat: 'alman_kultur', reg: 'nord', rar: 'common' },
  { term: 'Klönen', id: 'kloenen', meaningDe: 'Gemütliches Plaudern bei Tee oder Bier.', meaningEn: 'Having a cozy chat.', cat: 'alman_kultur', reg: 'nord', rar: 'common' },
  { term: 'Schietwetter', id: 'schietwetter', meaningDe: 'Norddeutsches Regen- und Schmuddelwetter.', meaningEn: 'Miserable rainy stormy Northern weather.', cat: 'alman_kultur', reg: 'nord', rar: 'common' },
  { term: 'Moin Moin', id: 'moin_moin', meaningDe: 'Doppeltes Moin (gilt im Norden oft als geschwätzig).', meaningEn: 'Chatty double Moin.', cat: 'alman_kultur', reg: 'nord', rar: 'rare' },
  { term: 'Deern', id: 'deern', meaningDe: 'Plattdeutsch für Mädchen.', meaningEn: 'Low German for young girl.', cat: 'alman_kultur', reg: 'nord', rar: 'common' },
  { term: 'Jung', id: 'jung_nord', meaningDe: 'Plattdeutsch für Junge / Bursche.', meaningEn: 'Low German for young boy.', cat: 'alman_kultur', reg: 'nord', rar: 'common' },
  { term: 'Kuddelmuddel', id: 'kuddelmuddel', meaningDe: 'Vollkommenes Chaos oder Durcheinander.', meaningEn: 'Complete mess, hodgepodge, clutter.', cat: 'jugendsprache', reg: 'nord', rar: 'common' },
  { term: 'Mumpitz', id: 'mumpitz', meaningDe: 'Völliger Blödsinn oder Humbug.', meaningEn: 'Nonsense, balderdash, bunkum.', cat: 'alman_kultur', reg: 'all', rar: 'rare' },
  { term: 'Kokolores', id: 'kokolores', meaningDe: 'Närrischer Unsinn oder Wichtigtuerei.', meaningEn: 'Nonsense, tomfoolery.', cat: 'alman_kultur', reg: 'all', rar: 'rare' },
  { term: 'Firlefanz', id: 'firlefanz', meaningDe: 'Überflüssiger Schnickschnack oder albernes Getue.', meaningEn: 'Trifles, knick-knacks, silly fuss.', cat: 'alman_kultur', reg: 'all', rar: 'common' },
  { term: 'Schnickschnack', id: 'schnickschnack', meaningDe: 'Unnötiges Zubehör oder leeres Gerede.', meaningEn: 'Bells and whistles, pointless bric-a-brac.', cat: 'alman_kultur', reg: 'all', rar: 'common' },
  { term: 'Kinkerlitzchen', id: 'kinkerlitzchen', meaningDe: 'Unbedeutende Kleinigkeiten oder Lappalien.', meaningEn: 'Trifles, petty details.', cat: 'alman_kultur', reg: 'all', rar: 'rare' },
  { term: 'Pillepalle', id: 'pillepalle', meaningDe: 'Einfache Kleinigkeit oder Kinderspiel.', meaningEn: 'Piece of cake, minor trivial matter.', cat: 'jugendsprache', reg: 'all', rar: 'common' },
  { term: 'Larifari', id: 'larifari', meaningDe: 'Nachlässiges, nicht ernsthaftes Handeln oder Gerede.', meaningEn: 'Flimflam, sloppy half-hearted behavior.', cat: 'alman_kultur', reg: 'bayern', rar: 'rare' },
  { term: 'Schlawiner', id: 'schlawiner', meaningDe: 'Raffinierter, gewitzter Gauner oder Charmeur.', meaningEn: 'Clever rascal, sly fox, charmer.', cat: 'flirten', reg: 'bayern', rar: 'common' },
  { term: 'Haudegen', id: 'haudegen', meaningDe: 'Erfahrener, kampferprobter und mutiger Typ.', meaningEn: 'Old warhorse, tough veteran.', cat: 'schimpf_ehre', reg: 'all', rar: 'rare' },
  { term: 'Tausendsassa', id: 'tausendsassa', meaningDe: 'Vielseitig begabter Mensch, der alles kann.', meaningEn: 'Jack-of-all-trades, versatile dynamo.', cat: 'schule_arbeit', reg: 'all', rar: 'legendary' },
  { term: 'Glückspilz', id: 'glueckspilz', meaningDe: 'Jemand, der ständig unverschämtes Glück hat.', meaningEn: 'Lucky dog, fortunate person.', cat: 'jugendsprache', reg: 'all', rar: 'common' },
  { term: 'Pechvogel', id: 'pechvogel', meaningDe: 'Jemand, dem ständig Missgeschicke passieren.', meaningEn: 'Jinx, unluckiest person.', cat: 'jugendsprache', reg: 'all', rar: 'common' },
  { term: 'Kummerspeck', id: 'kummerspeck', meaningDe: 'Gewichtszunahme durch Frustessen bei Liebeskummer.', meaningEn: 'Grief bacon (weight gained from comfort eating).', cat: 'food_drinks', reg: 'all', rar: 'legendary' },
  { term: 'Fernweh', id: 'fernweh', meaningDe: 'Die Sehnsucht nach fernen Ländern und Reisen.', meaningEn: 'Wanderlust, longing for distant places.', cat: 'alman_kultur', reg: 'all', rar: 'common' },
  { term: 'Weltschmerz', id: 'weltschmerz', meaningDe: 'Melancholische Trauer über die Unvollkommenheit der Welt.', meaningEn: 'World-weariness, deep philosophical sadness.', cat: 'alman_kultur', reg: 'all', rar: 'rare' },
  { term: 'Schadenfreude', id: 'schadenfreude', meaningDe: 'Die Freude über das Missgeschick anderer.', meaningEn: 'Malicious joy at another\'s misfortune.', cat: 'alman_kultur', reg: 'all', rar: 'common' },
  { term: 'Fremdschämen', id: 'fremdschaemen', meaningDe: 'Sich für das peinliche Verhalten anderer schämen.', meaningEn: 'Secondhand embarrassment for someone else.', cat: 'jugendsprache', reg: 'all', rar: 'common' },
  { term: 'Zechpreller', id: 'zechpreller', meaningDe: 'Jemand, der im Restaurant isst und ohne zu zahlen flieht.', meaningEn: 'Dine-and-dasher, bill dodger.', cat: 'food_drinks', reg: 'all', rar: 'rare' },
  { term: 'Geizkragen', id: 'geizkragen', meaningDe: 'Extrem knauserige Person, die ungern Geld ausgibt.', meaningEn: 'Scrooge, cheapskate, penny-pincher.', cat: 'alman_kultur', reg: 'all', rar: 'common' },
  { term: 'Schluckspecht', id: 'schluckspecht', meaningDe: 'Person, die gerne und viel Alkohol trinkt.', meaningEn: 'Heavy drinker, boozer, sponge.', cat: 'feiern', reg: 'all', rar: 'rare' },
  { term: 'Naschkatze', id: 'naschkatze', meaningDe: 'Jemand, der ständig Süßigkeiten und Snacks nascht.', meaningEn: 'Sweet tooth, snack lover.', cat: 'food_drinks', reg: 'all', rar: 'common' },
  { term: 'Bücherwurm', id: 'buecherwurm', meaningDe: 'Person, die ununterbrochen Bücher liest.', meaningEn: 'Bookworm, avid reader.', cat: 'schule_arbeit', reg: 'all', rar: 'common' },
  { term: 'Feierbiest', id: 'feierbiest', meaningDe: 'Jemand, der auf jeder Party bis zum Morgengrauen durchtanzt.', meaningEn: 'Party animal, unstoppable reveler.', cat: 'feiern', reg: 'all', rar: 'common' },
  { term: 'Partyhengst', id: 'partyhengst', meaningDe: 'Selbstbewusster Typ, der im Mittelpunkt jeder Feier steht.', meaningEn: 'Party stallion, charismatic party guy.', cat: 'feiern', reg: 'all', rar: 'rare' },
  { term: 'Draufgänger', id: 'draufgaenger', meaningDe: 'Mutiger, risikofreudiger Mensch ohne Angst.', meaningEn: 'Daredevil, reckless adventurer.', cat: 'schimpf_ehre', reg: 'all', rar: 'common' },
  { term: 'Spielverderber', id: 'spielverderber', meaningDe: 'Jemand, der anderen den Spaß verdirbt.', meaningEn: 'Killjoy, party pooper, buzzkill.', cat: 'feiern', reg: 'all', rar: 'common' },
  { term: 'Partymuffel', id: 'partymuffel', meaningDe: 'Jemand, der keine Lust auf Feiern und Trubel hat.', meaningEn: 'Party curmudgeon, homebody.', cat: 'feiern', reg: 'all', rar: 'common' },
  { term: 'Morgenmuffel', id: 'morgenmuffel', meaningDe: 'Person, die morgens nach dem Aufstehen schlechte Laune hat.', meaningEn: 'Morning grouch, not a morning person.', cat: 'alman_kultur', reg: 'all', rar: 'common' },
  { term: 'Nachteule', id: 'nachteule', meaningDe: 'Jemand, der am liebsten nachts wach und aktiv ist.', meaningEn: 'Night owl.', cat: 'feiern', reg: 'all', rar: 'common' },
  { term: 'Frühaufsteher', id: 'fruehaufsteher', meaningDe: 'Person, die freiwillig bei Sonnenaufgang aufsteht.', meaningEn: 'Early bird, morning person.', cat: 'schule_arbeit', reg: 'all', rar: 'common' },
  { term: 'Dauerschleife', id: 'dauerschleife', meaningDe: 'Ein Song oder Video, das man ununterbrochen wiederholt.', meaningEn: 'On infinite loop / repeat.', cat: 'jugendsprache', reg: 'all', rar: 'common' },
  { term: 'Ohrwurm', id: 'ohrwurm', meaningDe: 'Eine Melodie, die einem nicht mehr aus dem Kopf geht.', meaningEn: 'Earworm, catchy tune stuck in head.', cat: 'jugendsprache', reg: 'all', rar: 'common' },
  { term: 'Kopfkino', id: 'kopfkino', meaningDe: 'Lebhafte bildliche Fantasien im Kopf.', meaningEn: 'Mental cinema, vivid imagination.', cat: 'flirten', reg: 'all', rar: 'common' },
  { term: 'Bauchgefühl', id: 'bauchgefuehl', meaningDe: 'Intuitive Bauchentscheidung ohne langes Nachdenken.', meaningEn: 'Gut feeling, intuition.', cat: 'schule_arbeit', reg: 'all', rar: 'common' },
  { term: 'Gehirnjogging', id: 'gehirnjogging', meaningDe: 'Denksportaufgaben zur geistigen Fitness.', meaningEn: 'Brain training, mental workout.', cat: 'schule_arbeit', reg: 'all', rar: 'common' },
  { term: 'Denkpause', id: 'denkpause', meaningDe: 'Kurze Auszeit, um die Gedanken zu sortieren.', meaningEn: 'Breather for thought, brief hiatus.', cat: 'schule_arbeit', reg: 'all', rar: 'common' },
  { term: 'Affenhitze', id: 'affenhitze', meaningDe: 'Extrem drückende, unerträgliche Sommerhitze.', meaningEn: 'Scorching heat, blistering temperature.', cat: 'alman_kultur', reg: 'all', rar: 'common' },
  { term: 'Hundekälte', id: 'hundekaelte', meaningDe: 'Bittere, eisige Kälte im Winter.', meaningEn: 'Biting bitter cold.', cat: 'alman_kultur', reg: 'all', rar: 'common' },
  { term: 'Sauwetter', id: 'sauwetter', meaningDe: 'Furchtbares Regenwetter mit Matsch und Sturm.', meaningEn: 'Foul weather, beastly rain.', cat: 'alman_kultur', reg: 'all', rar: 'common' },
  { term: 'Kaiserwetter', id: 'kaiserwetter', meaningDe: 'Strahlend blauer Himmel und herrlicher Sonnenschein.', meaningEn: 'Glorious sunny weather, cloudless sky.', cat: 'alman_kultur', reg: 'wien', rar: 'common' },
  { term: 'Schmankerl', id: 'schmankerl', meaningDe: 'Bayerische & österreichische Delikatesse oder Leckerbissen.', meaningEn: 'Bavarian/Austrian culinary treat or gem.', cat: 'food_drinks', reg: 'bayern', rar: 'common' },
  { term: 'Hupfdohle', id: 'hupfdohle', meaningDe: 'Scherzhaft für eine etwas ungelenke Tänzerin.', meaningEn: 'Goofy dancing girl / chorus girl.', cat: 'feiern', reg: 'bayern', rar: 'rare' },
  { term: 'gschmeidig', id: 'gschmeidig', meaningDe: 'Geschmeidig, lässig, reibungslos oder cool.', meaningEn: 'Smooth, cool, slick.', cat: 'jugendsprache', reg: 'bayern', rar: 'common' },
  { term: 'Zefix', id: 'zefix', meaningDe: 'Traditioneller bayerischer Fluch bei Missgeschicken.', meaningEn: 'Traditional Bavarian curse word.', cat: 'schimpf_ehre', reg: 'bayern', rar: 'common' },
  { term: 'Kruzitürken', id: 'kruzituerken', meaningDe: 'Altbayerischer und österreichischer Fluch des Erstaunens.', meaningEn: 'Old Alpine exclamation of frustration.', cat: 'schimpf_ehre', reg: 'bayern', rar: 'rare' },
  { term: 'Haberer', id: 'haberer', meaningDe: 'Wienerischer Begriff für Kumpel, Spezl oder Freund.', meaningEn: 'Viennese term for friend or pal.', cat: 'jugendsprache', reg: 'wien', rar: 'common' },
  { term: 'Leiwand', id: 'leiwand', meaningDe: 'Typisch Wienerisch für großartig, genial oder super.', meaningEn: 'Awesome, terrific, fantastic (Vienna).', cat: 'jugendsprache', reg: 'wien', rar: 'legendary' },
  { term: 'Deppert', id: 'deppert', meaningDe: 'Dumm, blöd oder verrückt (Österreich & Bayern).', meaningEn: 'Stupid, foolish, silly (Alpine).', cat: 'schimpf_ehre', reg: 'wien', rar: 'common' },
  { term: 'Gspusi', id: 'gspusi', meaningDe: 'Eine kleine heimliche Liebschaft oder Affäre.', meaningEn: 'Secret romance, fling, sweetheart.', cat: 'flirten', reg: 'bayern', rar: 'common' },
  { term: 'Tschick', id: 'tschick', meaningDe: 'Österreichisch für Zigarette.', meaningEn: 'Austrian slang for cigarette.', cat: 'feiern', reg: 'wien', rar: 'common' },
  { term: 'Krügerl', id: 'kruegerl', meaningDe: 'Ein halber Liter Bier in Österreich.', meaningEn: 'Half liter pint of beer in Austria.', cat: 'food_drinks', reg: 'wien', rar: 'common' },
  { term: 'Melange', id: 'melange', meaningDe: 'Traditionelle Wiener Kaffeespezialität mit Milchschaum.', meaningEn: 'Traditional Viennese coffee with milk foam.', cat: 'food_drinks', reg: 'wien', rar: 'common' },
  { term: 'Sachertorte', id: 'sachertorte', meaningDe: 'Weltberühmte Wiener Schokoladentorte mit Marillenmarmelade.', meaningEn: 'Iconic Viennese chocolate apricot cake.', cat: 'food_drinks', reg: 'wien', rar: 'common' },
  { term: 'Beisl', id: 'beisl', meaningDe: 'Gemütliches traditionelles Wiener Gasthaus.', meaningEn: 'Traditional cozy Viennese bistro pub.', cat: 'food_drinks', reg: 'wien', rar: 'common' },
  { term: 'Schanigarten', id: 'schanigarten', meaningDe: 'Der Freiluftbereich eines Wiener Kaffeehauses.', meaningEn: 'Outdoor seating patio in Vienna.', cat: 'food_drinks', reg: 'wien', rar: 'common' },
  { term: 'Chuchichäschtli', id: 'chuchichaeschtli', meaningDe: 'Küchenschränkchen (der berühmteste Schweizerdeutsch-Zungenbrecher).', meaningEn: 'Kitchen cabinet (famous Swiss shibboleth).', cat: 'alman_kultur', reg: 'schweiz', rar: 'legendary' },
  { term: 'Merci vilmal', id: 'merci_vilmal', meaningDe: 'Schweizerdeutsch für "Vielen herzlichen Dank".', meaningEn: 'Thank you very much in Swiss German.', cat: 'alman_kultur', reg: 'schweiz', rar: 'common' },
  { term: 'Stutz', id: 'stutz', meaningDe: 'Schweizerdeutsch für Franken / Geld.', meaningEn: 'Swiss slang for Swiss Francs / money.', cat: 'schule_arbeit', reg: 'schweiz', rar: 'common' },
  { term: 'Bünzli', id: 'buenzli', meaningDe: 'Der Schweizer Inbegriff des überkorrekten Spießbürgers.', meaningEn: 'The ultimate Swiss rule-obsessed conformist.', cat: 'alman_kultur', reg: 'schweiz', rar: 'legendary' },
  { term: 'Apéro', id: 'apero', meaningDe: 'Schweizer Geselligkeitsritual mit Drinks und Knabbereien.', meaningEn: 'Swiss social after-work drinks & bites.', cat: 'feiern', reg: 'schweiz', rar: 'common' },
  { term: 'Zmorge', id: 'zmorge', meaningDe: 'Schweizerdeutsch für Frühstück.', meaningEn: 'Swiss German for breakfast.', cat: 'food_drinks', reg: 'schweiz', rar: 'common' },
  { term: 'Zvieri', id: 'zvieri', meaningDe: 'Schweizer Nachmittagssnack um vier Uhr.', meaningEn: 'Swiss 4 PM afternoon tea/snack.', cat: 'food_drinks', reg: 'schweiz', rar: 'common' },
  { term: 'Znacht', id: 'znacht', meaningDe: 'Schweizerdeutsch für Abendessen.', meaningEn: 'Swiss German for dinner.', cat: 'food_drinks', reg: 'schweiz', rar: 'common' },
  { term: 'Chrampfe', id: 'chrampfe', meaningDe: 'Schweizerdeutsch für hart schuften oder büffeln.', meaningEn: 'Swiss slang for working or grinding hard.', cat: 'schule_arbeit', reg: 'schweiz', rar: 'common' },
  { term: 'Röschtigrabe', id: 'roeschtigrabe', meaningDe: 'Die kulturelle Grenze zwischen Deutsch- und Westschweiz.', meaningEn: 'Cultural divide between German and French Switzerland.', cat: 'alman_kultur', reg: 'schweiz', rar: 'rare' },
  { term: 'Zmittag', id: 'zmittag', meaningDe: 'Schweizerdeutsch für Mittagessen.', meaningEn: 'Swiss German for lunch.', cat: 'food_drinks', reg: 'schweiz', rar: 'common' },
  { term: 'Schoggi', id: 'schoggi', meaningDe: 'Schweizer Schokolade.', meaningEn: 'Swiss chocolate.', cat: 'food_drinks', reg: 'schweiz', rar: 'common' },
  { term: 'Fondue', id: 'fondue', meaningDe: 'Geschmolzener Käsetopf zum Eintauchen von Brotwürfeln.', meaningEn: 'Melted cheese fondue dip pot.', cat: 'food_drinks', reg: 'schweiz', rar: 'common' },
  { term: 'Raclette', id: 'raclette', meaningDe: 'Geschmolzener Käse auf Kartoffeln und Essiggurken.', meaningEn: 'Melted raclette cheese on potatoes.', cat: 'food_drinks', reg: 'schweiz', rar: 'common' }
];

console.log(`Extra handcrafted entries: ${extraSlang.length}, base extra words: ${additionalVocabList.length}`);

// We will generate complete 300+ SlangWord items with full dialogue scenarios, hints, and distractors.
